sylius_grid:
    grids:
        app_backend_page:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Page
            sorting:
                title: asc
            fields:
                id:
                    type: string
                    label: app.ui.id
                title:
                    type: string
                    sortable: ~
                    label: app.ui.title
            filters:
                title:
                    type: string

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete