sylius_grid:
    grids:
        app_backend_page:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\Page
            sorting:
                title: asc
            limits: [2,4,6]

            fields:
                id:
                    type: string
                    label: app.ui.id
                permalink:
                    type: string
                    label: app.ui.permalink
                    sortable: ~
                title:
                    type: string
                    sortable: ~
                    label: app.ui.title
                created_at:
                    type: datetime
                    label: app.ui.created_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
#            filters:
#                title:
#                    type: string
#                id:
#                   type: string

            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete