sylius_grid:
    grids:
        app_backend_user:
            driver:
                name: doctrine/orm
                options:
                    class: AppBundle\Entity\User
            fields:
                username:
                    type: string
                    label: sylius.ui.username
                email:
                    type: string
                    label: sylius.ui.email
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete