# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
        app_backend_user_provider:
            id: sylius.backend_user_provider.email_or_name_based
        app_frontend_user_provider:
            id: sylius.frontend_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512

    firewalls:
        backend:
            switch_user: true
            context: backend
            pattern: /backend(?:/.*)?$
            form_login:
                provider: app_backend_user_provider
                login_path: app_backend_login
                check_path: app_backend_login_check
                failure_path: app_backend_login
                default_target_path: app_backend_dashboard
                use_forward: false
                use_referer: true
            logout:
                path: app_backend_logout
                target: app_backend_login
            anonymous: true

#        oauth_token:
#            pattern:  ^/api/oauth/v2/token
#            security: false
#
#        api:
#            pattern:    ^/api
#            fos_oauth:  true
#            stateless:  true
#            anonymous:  true

        frontend:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: shop
            pattern: /.*
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: app_frontend_user_provider
                login_path: app_frontend_login
                check_path: app_frontend_login_check
                failure_path: app_frontend_login
                default_target_path: app_frontend_homepage
                use_forward: false
                use_referer: true
            remember_me:
                secret: "%secret%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            logout:
                path: app_frontend_logout
                target: app_frontend_login
                invalidate_session: false
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: "/account.*", role: ROLE_USER }

        - { path: ^/backend/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/login-check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/backend.*", role: ROLE_ADMINISTRATION_ACCESS }

#        - { path: ^/api, role: ROLE_API_ACCESS }

#        - { path: "/_partial.*", ip: 127.0.0.1 }