app_backend_user:
    resource: |
        alias: sylius.backend_user
        section: backend
        templates: :Crud
        except: ['show']
        redirect: index
        grid: app_backend_user
        vars:
            all:
                subheader: app.ui.user # define a translation key for your entity subheader
            index:
                icon: 'file image outline' # choose an icon that will be displayed next to the subheader
    type: sylius.resource

#app_backend_user_index:
#    path: /
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.backend_user:indexAction
#        _sylius:
#            template: SyliusWebBundle:Backend/Customer:index.html.twig
#            sortable: true
#
#app_backend_user_create:
#    path: /new
#    methods: [GET, POST]
#    defaults:
#        _controller: sylius.controller.backend_user:createAction
#        _sylius:
#            template: SyliusWebBundle:Backend/Customer:create.html.twig
#            redirect: app_backend_user_show
#
#app_backend_user_update:
#    path: /{id}/edit
#    methods: [GET, PUT, POST]
#    defaults:
#        _controller: sylius.controller.backend_user:updateAction
#        _sylius:
#            template: SyliusWebBundle:Backend/Customer:update.html.twig
#            redirect: app_backend_user_show
#
#app_backend_user_show:
#    path: /{id}
#    methods: [GET]
#    defaults:
#        _controller: sylius.controller.backend_user:showAction
#        _sylius:
#            template: SyliusWebBundle:Backend/Customer:show.html.twig
#            repository:
#                method: findForDetailsPage
#                arguments: [$id]
