app_frontend_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: AppBundle:Frontend/Security:login

app_frontend_login_check:
    path: /login-check
    defaults:
        _controller: AppBundle:Frontend/Security:check

app_frontend_logout:
    path: /logout
    defaults:
        _controller: AppBundle:Frontend/Security:logout


#app_frontend_register:
#    path: /register
#    methods: [GET, POST]
#    defaults:
#        _controller: sylius.controller.customer:createAction
#        _sylius:
#            template: "@SyliusShop/register.html.twig"
#            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
#            event: register
#            redirect:
#                route: app_frontend_homepage
#            flash: sylius.customer.register

app_frontend_request_password_reset_token:
    path: /forgotten-password
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.frontend_user:requestPasswordResetTokenAction
        _sylius:
            template: "@SyliusShop/Account/requestPasswordReset.html.twig"
            redirect: app_frontend_login

app_frontend_password_reset:
    path: /forgotten-password/{token}
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.frontend_user:resetPasswordAction
        _sylius:
            template: "@SyliusShop/Account/resetPassword.html.twig"
            redirect: app_frontend_login
